### ISSUE TITLE
Links to explore tool are broken/missing in HTML resultset from Radial or Rectangular Search Forms

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#26]
Test: s_rad_search_4 and s_rect_search_4

**Comment by mtaghiza** [comment]
Ani realized that the links are broken since the current SkyServer's URL (obtained from a database query) is missing a '/DR12' right before '/en/tools/...' 
We should add the '/DR12' for all URLs.

**Comment by thakar** [comment]
The links are broken in the Radial results, and they are altogether missing in the Rectangular results.

**Comment by mtaghiza** [comment]
Fixed. These Links appear now in all HTML resultsets.
However, these links appear broken due to the extra 'DR12' string in the URL.

**Comment by thakar** [comment]
No, the links still do not appear in the Rectangular search results.

**Comment by mtaghiza** [comment]
Fixed now for Rectangular search. Will work correctly in next version.

**Comment by raddick** [comment]
Not working in sciserver_v1_2_0 .

The links display correctly, but they go to the wrong page. Returns the following error:

Server Error in '/SkyServer' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /Skyserver/dr12/en/tools/explore/summary.aspx

**Comment by mtaghiza** [comment]
This is related to issue #41.

**Comment by raddick** [comment]
Fixed.
